server:
  port: 8080


spring:
  redis:
    port: 6379
    database: 0
    host: 39.101.166.92
    password: wwwwww
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 30000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: wwwwww
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 1
      # 最小连接池数量
      minIdle: 1
      # 最大连接池数量
      maxActive: 10
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 验证连接有效与否的SQL，不同的数据配置不同
      validationQuery: select 1
      # 建议配置为true，不影响性能，并且保证安全性。
      # 申请连接的时候检测，如果空闲时间大于
      # timeBetweenEvictionRunsMillis，
      # 执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      # 这里建议配置为TRUE，防止取到的连接不可用
      testOnBorrow: true
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache。
      # PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      # 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      # 作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录，
      # 该应该是支持PSCache。
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 属性类型是字符串，通过别名的方式配置扩展插件，
      # 常用的插件有：
      # 监控统计用的filter:stat
      # 日志用的filter:log4j
      # 防御sql注入的filter:wall
      filters: stat

# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/cn/jonwong/oauth/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.jongwong.oauth.entity
#  type-enums-package: cn.jongwong.oauth.enums


yoohoo:
  oauth:
    domain: http://localhost:8080


